# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bb7005b2d90ea331cba2628da2dd4dbe4c8ac9bdf3563b17449ba2825b1155f00b8ef59f68266a46283573a05472aee55b19ee6234dfa9a42ab114aa3158715

test:
  secret_key_base: 870bb4189f1788c7ffeb2286d4bbadfc9217da576ebd8b90d2c0f2113f3382d20b8ece428500b346938975974c878a2886bba7c59cd4ebe8bac3fa255f10d4d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
